name: Update Statistics Brainly.co.id

on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │  ┌───────────── day of the month (1 - 31)
    #        │ │  │  ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │  │  │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │  │  │ │
    #        │ │  │  │ │
    #        │ │  │  │ │
    #        * *  *  * *
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  updateStats:
    runs-on: ubuntu-latest
    name: Update statistics
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Setup PHP
        uses: shivammathur/setup-php@73963f5001e335723c998e4a0125ce060083985c # v2.30.1
        with:
          php-version: "8.3"
          extensions: curl

      # Fix the unsafe repo error which was introduced by the CVE-2022-24765 git patches.
      - name: Fix unsafe repo error
        run: git config --global --add safe.directory ${{ github.workspace }}

      - name: Update git repository
        run: git pull

      - name: Run script
        run: php stats.php
        env:
          BR_TOKEN: ${{ secrets.BRAINLY_PERSONAL_TOKEN }}

      - name: Set up Git
        run: |
          git config user.name "fazbrainly"
          git config user.email "146303897+fazbrainly@users.noreply.github.com"
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: Push commit to a new branch and create pull request
        run: |
          branch="update_stats"
          message="doc: update statistics"
          if [[ "$(git status --porcelain)" != "" ]]; then
            git branch -D ${branch} || true
            git checkout -b ${branch}
            git add README.md
            git commit --message "${message}"
            git remote add origin-${branch} "https://github.com/fazbrainly/fazbrainly.git"
            git push --force --quiet --set-upstream origin-${branch} ${branch}
            gh pr create --title "${message}" --body ""
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
